### ISSUE TITLE
Associated hardware is claimed open source, but source is not available

### ISSUE THREAD

**Issue by zbrozek** [banichow/OctoPrint-Atxpihat#1]
I don't see hardware sources available anywhere, but the linked storefront claims that the hardware is open source. Ideally post the schematics and layouts to the github repository. Or, less ideally, don't claim the hardware as open source.

**Comment by banichow** [comment]
Thank you for the note and the concern. The schematics are available on my site https://www.baprojectworkshop.com in the ATXPiHat section. Also the software to run the board is available here. I feel confident that this meets all of the criteria. Please let me know if there are any further questions.

Warm regards,
--BA
